use trm_db;

-- 初始化角色
truncate table qm_role_t;
insert into qm_role_t (role_name, creation_date, last_update_date)
values ('System Admin', now(), now());

-- 币种初始化
truncate table trm_currency_t;
INSERT INTO trm_currency_t (currency_code, currency_name, description, amount_precision, rate_precision, rounding_method, currency_holidays, day_count_convention, delete_flag, creation_date, created_by, last_update_date, last_updated_by)
VALUES
('AED', 'United Arab Emirates Dirham', 'The currency of the United Arab Emirates.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AFN', 'Afghan Afghani', 'The currency of Afghanistan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ALL', 'Albanian Lek', 'The currency of Albania.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AMD', 'Armenian Dram', 'The currency of Armenia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ANG', 'Netherlands Antillean Guilder', 'The currency of the Netherlands Antilles.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AOA', 'Angolan Kwanza', 'The currency of Angola.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ARS', 'Argentine Peso', 'The currency of Argentina.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AUD', 'Australian Dollar', 'The currency of Australia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AWG', 'Aruban Florin', 'The currency of Aruba.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('AZN', 'Azerbaijani Manat', 'The currency of Azerbaijan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BAM', 'Bosnia and Herzegovina Convertible Mark', 'The currency of Bosnia and Herzegovina.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BBD', 'Barbadian Dollar', 'The currency of Barbados.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BDT', 'Bangladeshi Taka', 'The currency of Bangladesh.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BGN', 'Bulgarian Lev', 'The currency of Bulgaria.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BHD', 'Bahraini Dinar', 'The currency of Bahrain.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BIF', 'Burundian Franc', 'The currency of Burundi.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BMD', 'Bermudian Dollar', 'The currency of Bermuda.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BND', 'Brunei Dollar', 'The currency of Brunei.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BOB', 'Bolivian Boliviano', 'The currency of Bolivia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BRL', 'Brazilian Real', 'The currency of Brazil.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BSD', 'Bahamian Dollar', 'The currency of the Bahamas.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BTN', 'Bhutanese Ngultrum', 'The currency of Bhutan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BWP', 'Botswana Pula', 'The currency of Botswana.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BYN', 'Belarusian Ruble', 'The currency of Belarus.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('BZD', 'Belize Dollar', 'The currency of Belize.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CAD', 'Canadian Dollar', 'The currency of Canada.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CDF', 'Congolese Franc', 'The currency of the Democratic Republic of the Congo.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CHF', 'Swiss Franc', 'The currency of Switzerland.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CLP', 'Chilean Peso', 'The currency of Chile.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CNY', 'Chinese Yuan', 'The currency of China.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('COP', 'Colombian Peso', 'The currency of Colombia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CRC', 'Costa Rican Colón', 'The currency of Costa Rica.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CUC', 'Cuban Convertible Peso', 'The currency of Cuba.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CUP', 'Cuban Peso', 'The currency of Cuba.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CVE', 'Cape Verdean Escudo', 'The currency of Cape Verde.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CZK', 'Czech Koruna', 'The currency of the Czech Republic.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('DJF', 'Djiboutian Franc', 'The currency of Djibouti.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('DKK', 'Danish Krone', 'The currency of Denmark.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('DOP', 'Dominican Peso', 'The currency of the Dominican Republic.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('DZD', 'Algerian Dinar', 'The currency of Algeria.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1);

INSERT INTO trm_currency_t (currency_code, currency_name, description, amount_precision, rate_precision, rounding_method, currency_holidays, day_count_convention, delete_flag, creation_date, created_by, last_update_date, last_updated_by)
VALUES
('EGP', 'Egyptian Pound', 'The currency of Egypt.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ERN', 'Eritrean Nakfa', 'The currency of Eritrea.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ESA', 'Spanish Peseta (A)', 'The currency of Spain (A).', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ESB', 'Spanish Peseta (B)', 'The currency of Spain (B).', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ESP', 'Spanish Peseta', 'The currency of Spain.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ETB', 'Ethiopian Birr', 'The currency of Ethiopia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('EUR', 'Euro', 'The currency of the Eurozone.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('FJD', 'Fijian Dollar', 'The currency of Fiji.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('FKP', 'Falkland Islands Pound', 'The currency of the Falkland Islands.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GBP', 'British Pound Sterling', 'The currency of the United Kingdom.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GEL', 'Georgian Lari', 'The currency of Georgia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GHS', 'Ghanaian Cedi', 'The currency of Ghana.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GIP', 'Gibraltar Pound', 'The currency of Gibraltar.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GMD', 'Gambian Dalasi', 'The currency of The Gambia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GNF', 'Guinean Franc', 'The currency of Guinea.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GWP', 'Guinea-Bissau Peso', 'The currency of Guinea-Bissau.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('GYD', 'Guyanese Dollar', 'The currency of Guyana.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('HKD', 'Hong Kong Dollar', 'The currency of Hong Kong.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('HNL', 'Honduran Lempira', 'The currency of Honduras.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('HRK', 'Croatian Kuna', 'The currency of Croatia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('HTG', 'Haitian Gourde', 'The currency of Haiti.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('HUF', 'Hungarian Forint', 'The currency of Hungary.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('IDR', 'Indonesian Rupiah', 'The currency of Indonesia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ILS', 'Israeli New Shekel', 'The currency of Israel.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('INR', 'Indian Rupee', 'The currency of India.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('IQD', 'Iraqi Dinar', 'The currency of Iraq.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('IRR', 'Iranian Rial', 'The currency of Iran.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ISK', 'Icelandic Krona', 'The currency of Iceland.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('JMD', 'Jamaican Dollar', 'The currency of Jamaica.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('JOD', 'Jordanian Dinar', 'The currency of Jordan.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('JPY', 'Japanese Yen', 'The currency of Japan.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KES', 'Kenyan Shilling', 'The currency of Kenya.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KGS', 'Kyrgyzstani Som', 'The currency of Kyrgyzstan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KHR', 'Cambodian Riel', 'The currency of Cambodia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KMF', 'Comorian Franc', 'The currency of Comoros.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KRW', 'South Korean Won', 'The currency of South Korea.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KWD', 'Kuwaiti Dinar', 'The currency of Kuwait.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KYD', 'Cayman Islands Dollar', 'The currency of the Cayman Islands.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('KZT', 'Kazakhstani Tenge', 'The currency of Kazakhstan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('LAK', 'Laotian Kip', 'The currency of Laos.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1);

INSERT INTO trm_currency_t (currency_code, currency_name, description, amount_precision, rate_precision, rounding_method, currency_holidays, day_count_convention, delete_flag, creation_date, created_by, last_update_date, last_updated_by)
VALUES
('MAD', 'Moroccan Dirham', 'The currency of Morocco.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MDL', 'Moldovan Leu', 'The currency of Moldova.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MGA', 'Malagasy Ariary', 'The currency of Madagascar.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MKD', 'Macedonian Denar', 'The currency of North Macedonia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MMK', 'Myanma Kyat', 'The currency of Myanmar.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MNT', 'Mongolian Tugrik', 'The currency of Mongolia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MOP', 'Macanese Pataca', 'The currency of Macau.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MRO', 'Mauritanian Ouguiya', 'The currency of Mauritania.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MRU', 'Mauritanian Ouguiya (new)', 'The currency of Mauritania (new)', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MUR', 'Mauritian Rupee', 'The currency of Mauritius.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MVR', 'Maldivian Rufiyaa', 'The currency of the Maldives.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MWK', 'Malawian Kwacha', 'The currency of Malawi.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MXN', 'Mexican Peso', 'The currency of Mexico.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MYR', 'Malaysian Ringgit', 'The currency of Malaysia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('MZN', 'Mozambican Metical', 'The currency of Mozambique.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NAD', 'Namibian Dollar', 'The currency of Namibia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NGN', 'Nigerian Naira', 'The currency of Nigeria.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NIO', 'Nicaraguan Córdoba', 'The currency of Nicaragua.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NOK', 'Norwegian Krone', 'The currency of Norway.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NPR', 'Nepalese Rupee', 'The currency of Nepal.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('NZD', 'New Zealand Dollar', 'The currency of New Zealand.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('OMR', 'Omani Rial', 'The currency of Oman.', 3, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PAB', 'Panamanian Balboa', 'The currency of Panama.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PEN', 'Peruvian Nuevo Sol', 'The currency of Peru.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PGK', 'Papua New Guinean Kina', 'The currency of Papua New Guinea.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PHP', 'Philippine Peso', 'The currency of the Philippines.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PKR', 'Pakistani Rupee', 'The currency of Pakistan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PLN', 'Polish Zloty', 'The currency of Poland.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('PYG', 'Paraguayan Guarani', 'The currency of Paraguay.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('QAR', 'Qatari Rial', 'The currency of Qatar.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('RON', 'Romanian Leu', 'The currency of Romania.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('RSD', 'Serbian Dinar', 'The currency of Serbia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('RUB', 'Russian Ruble', 'The currency of Russia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('RWF', 'Rwandan Franc', 'The currency of Rwanda.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SAR', 'Saudi Riyal', 'The currency of Saudi Arabia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SBD', 'Solomon Islands Dollar', 'The currency of the Solomon Islands.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SCR', 'Seychellois Rupee', 'The currency of Seychelles.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SDG', 'Sudanese Pound', 'The currency of Sudan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SEK', 'Swedish Krona', 'The currency of Sweden.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SGD', 'Singapore Dollar', 'The currency of Singapore.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SHP', 'Saint Helena Pound', 'The currency of Saint Helena.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SLL', 'Sierra Leonean Leone', 'The currency of Sierra Leone.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SOS', 'Somali Shilling', 'The currency of Somalia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SRD', 'Surinamese Dollar', 'The currency of Suriname.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SSP', 'South Sudanese Pound', 'The currency of South Sudan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('STN', 'São Tomé and Príncipe Dobra', 'The currency of São Tomé and Príncipe.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SVC', 'Salvadoran Colón', 'The currency of El Salvador.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SYP', 'Syrian Pound', 'The currency of Syria.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('SZL', 'Swazi Lilangeni', 'The currency of Swaziland (now Eswatini).', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('THB', 'Thai Baht', 'The currency of Thailand.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('TJS', 'Tajikistani Somoni', 'The currency of Tajikistan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('TMT', 'Turkmenistani Manat', 'The currency of Turkmenistan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1);

INSERT INTO trm_currency_t (currency_code, currency_name, description, amount_precision, rate_precision, rounding_method, currency_holidays, day_count_convention, delete_flag, creation_date, created_by, last_update_date, last_updated_by)
VALUES
('UAH', 'Ukrainian Hryvnia', 'The currency of Ukraine.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('UGX', 'Ugandan Shilling', 'The currency of Uganda.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('UYU', 'Uruguayan Peso', 'The currency of Uruguay.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('UZS', 'Uzbekistani Som', 'The currency of Uzbekistan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('VEF', 'Venezuelan Bolívar', 'The currency of Venezuela.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('VND', 'Vietnamese Dong', 'The currency of Vietnam.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('VUV', 'Vanuatu Vatu', 'The currency of Vanuatu.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('WST', 'Samoan Tala', 'The currency of Samoa.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XAF', 'CFA Franc (XAF)', 'The currency used in many central African countries.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XAG', 'Silver Ounce', 'The currency representing one ounce of silver.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XAU', 'Gold Ounce', 'The currency representing one ounce of gold.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XDR', 'Special Drawing Rights', 'The international reserve asset created by the IMF.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XOF', 'CFA Franc (XOF)', 'The currency used in many West African countries.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('XPF', 'CFP Franc', 'The currency used in French Polynesia, New Caledonia, and Wallis and Futuna.', 0, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('YER', 'Yemeni Rial', 'The currency of Yemen.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ZAR', 'South African Rand', 'The currency of South Africa.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ZMW', 'Zambian Kwacha', 'The currency of Zambia.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/365', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('ZWL', 'Zimbabwean Dollar', 'The currency of Zimbabwe.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1);

INSERT INTO trm_currency_t (currency_code, currency_name, description, amount_precision, rate_precision, rounding_method, currency_holidays, day_count_convention, delete_flag, creation_date, created_by, last_update_date, last_updated_by)
VALUES
('TWD', 'New Taiwan Dollar', 'The currency of Taiwan.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1),
('CNH', 'Offshore Renminbi', 'The offshore version of the Chinese Yuan, used outside Mainland China.', 2, 4, 'ROUND_HALF_UP', '', 'Actual/360', 'N', CURRENT_TIMESTAMP, -1, CURRENT_TIMESTAMP, -1);
